# Generated by Django 3.2 on 2021-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210602_2216'),
        ('dashboard', '0002_auto_20210604_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyspend',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='dailyspend',
            name='total_daily_meals',
        ),
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyspend',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='editors',
            field=models.ManyToManyField(null=True, to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='elec_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='food_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='gas_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='house_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='members',
            field=models.ManyToManyField(null=True, to='dashboard.Person'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='other_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='water_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
