# Generated by Django 3.2 on 2021-06-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210604_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='members',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_members',
        ),
        migrations.DeleteModel(
            name='PerPersonMeal',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
