# Generated by Django 3.2 on 2021-06-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_budget_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyspend',
            old_name='amount',
            new_name='amount_Spent',
        ),
    ]
