# Generated by Django 3.2 on 2021-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('blue', 'Kinda Blue'), ('coral', 'Living Coral'), ('green', 'Pastel Green'), ('purple', 'Lavender'), ('white', 'Not So White')], default='white', max_length=30),
        ),
    ]
