# Generated by Django 3.2 on 2021-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'Kinda Blue'), ('coral', 'Living Coral'), ('green', 'Pastel Green'), ('purple', 'Lavender'), ('white', 'Not So White'), ('teal', 'Ocean Green')], default='white', max_length=30),
        ),
    ]
