# Generated by Django 3.2 on 2021-04-09 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('institution', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
